# Etapa 1: build da aplicação
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copia os arquivos do projeto
COPY *.sln .
COPY WhatsDjBotAPI/*.csproj ./WhatsDjBotAPI/
RUN dotnet restore

COPY . .
WORKDIR /app/WhatsDjBotAPI
RUN dotnet publish -c Release -o out

# Etapa 2: imagem final para execução
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/WhatsDjBotAPI/out ./

# Porta padrão do ASP.NET
EXPOSE 80

# Variável de ambiente para o ASP.NET saber que está em produção
ENV ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "WhatsDjBotAPI.dll"]
